name: master-build-pages
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: SetNodeVersion
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
    - name: Build
      run: | 
        ls -la
        ls blog -la
        npm install 
        npm run linux-build  
        echo 'blog.haiyinlong.cn' > public/CNAME
        ls public -la
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        BRANCH: gh-pages
        FOLDER: public
    